#!/usr/bin/env python3
"""
PersonaPlex v3 — Workstation Brain Client
==========================================
Connects to the PersonaPlex gateway on the Spark.
  Receives: AI audio (plays speakers) + transcript text + turn.boundary events
  Sends:    Human mic audio + node commands

Brain architecture:
  Gemini 1 — DETECTOR  (google-genai Live API, persistent WebSocket)
    - Receives transcript deltas silently (turn_complete=False)
    - On every turn.boundary "human_end": evaluates with turn_complete=True
    - Responds: CONTINUE or ACTION_NEEDED + reason/topic
    - Reconnects every ~9 min injecting full transcript for continuity

  Gemini 2 — COMPRESSOR  (google-generativeai Flash, REST, context caching)
    - Called when brain decides ACTION_NEEDED or keepalive timer fires
    - Reads full local transcript, produces 300-500 token boot payload
    - Context caching: only pays for new transcript delta per call

Node flow:
  Keepalive (every 170s):
    Compressor → boot_payload → node.refresh → standby primed
    → node.standby_ready → node.switch(standby) → node.stop(filler) reset

  ACTION_NEEDED:
    node.switch(filler) immediately
    Compressor → boot_payload → node.prime(standby)
    → node.standby_ready → node.switch(standby) + node.stop(filler)

Usage:
  pip install websockets sounddevice numpy google-genai google-generativeai

  export GOOGLE_API_KEY=AIza...
  python brain_client.py --host 192.168.2.117 --port 8998 \\
      --persona "You are Jane, a curious AI who loves science." \\
      --voice NATF0

  # Without brain (audio-only test):
  python brain_client.py --host 192.168.2.117 --no-brain
"""

import argparse
import asyncio
import base64
import datetime
import json
import os
import queue
import sys
import threading
import time
from typing import Optional

try:
    import websockets
except ImportError:
    print("ERROR: pip install websockets"); sys.exit(1)

try:
    import numpy as np
except ImportError:
    print("ERROR: pip install numpy"); sys.exit(1)

try:
    import sounddevice as sd
except (ImportError, OSError):
    sd = None
    print("WARNING: sounddevice not available — mic/speaker mode disabled")

try:
    from google import genai as live_genai
    from google.genai import types as live_types
    _LIVE_GENAI = True
    _REST_GENAI  = True   # same package handles both Live and REST
except ImportError:
    _LIVE_GENAI = False
    _REST_GENAI  = False
    print("WARNING: pip install google-genai — Brain (Detector + Compressor) disabled")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
INPUT_RATE  = 24000
OUTPUT_RATE = 48000
FRAME_MS    = 80
FRAME_SAMPLES_IN  = INPUT_RATE  * FRAME_MS // 1000   # 1920
FRAME_SAMPLES_OUT = OUTPUT_RATE * FRAME_MS // 1000   # 3840

DETECTOR_MODEL   = "gemini-live-2.5-flash-preview"          # Live API (bidiGenerateContent)
COMPRESSOR_MODEL = "gemini-2.0-flash-001"                  # REST API (stable)

# Keepalive: prime standby every N seconds to prevent prompt amnesia (4-min window)
KEEPALIVE_INTERVAL_S = 170   # 2 min 50 sec — safe margin before 4-min forgetfulness

# Detector Live session max age before reconnect (Google cap ~10 min)
LIVE_SESSION_MAX_S = 520      # ~8.5 min — reconnect proactively

# Compressor context caching: refresh cache every N new chars of transcript
CACHE_REFRESH_CHARS = 2000    # ~500 new tokens

# Min transcript length before brain starts evaluating
BRAIN_MIN_CHARS = 80

# Boot payload target size (characters) — must fit PP's ~1000 token window
BOOT_PAYLOAD_MAX_CHARS = 3500

VOICE_NAMES = [
    "NATF0","NATF1","NATF2","NATF3",
    "NATM0","NATM1","NATM2","NATM3",
    "VARF0","VARF1","VARF2","VARF3","VARF4",
    "VARM0","VARM1","VARM2","VARM3","VARM4",
]
VOICE_SENTINEL      = -999   # prefix: voice name follows as ASCII int32s
VOICE_TEXT_SENTINEL = -998   # separator: SentencePiece text tokens follow

# Pre-tokenised filler instruction using Moshi's SentencePiece tokeniser.
# Generated by: python3 tools/check_voices.py on the Spark (nvidia/personaplex-7b-v1).
# Conditions filler PP: "hold on / just a moment" variants only, never answer questions.
FILLER_TEXT_TOKENS: list[int] = [
    493, 298, 6578, 8660, 5649, 263, 5948, 378, 908, 261, 5014, 21705, 15705,
    418, 590, 15098, 272, 2266, 286, 261, 590, 539, 1656, 291, 272, 9523, 286,
    261, 590, 431, 6689, 288, 477, 286, 261, 590, 8443, 2266, 1834, 286, 261,
    590, 461, 286, 615, 297, 583, 288, 304, 286, 261, 590, 15098, 272, 557, 286,
    263, 9455, 666, 1292, 263, 9455, 9157, 568, 263, 447, 1644, 1421, 261, 4816,
    378, 288, 659, 2944, 264, 590, 6708, 272, 2266, 286, 263,
]

# ---------------------------------------------------------------------------
# Prompt templates
# ---------------------------------------------------------------------------

DETECTOR_SYSTEM = """\
You are the brain for a voice AI agent.
AI Persona: {persona}

You receive the AI's transcript incrementally.
When prompted to evaluate, respond with EXACTLY ONE of:

CONTINUE
  (the AI can handle the conversation with its current context)

ACTION_NEEDED
[REASON] <one sentence: why the AI cannot answer without new information>
[TOPIC] <the specific question or knowledge gap>

Critical rules:
- Default is CONTINUE. Most turns should be CONTINUE.
- Only say ACTION_NEEDED when the user asked something the AI genuinely
  cannot know from the conversation so far (real-time data, specific facts
  not established, tool calls needed).
- PP currently knows: {current_pp_context}
- Never add commentary or markdown. Exact format only.
"""

DETECTOR_EVAL_PROMPT = (
    "Evaluate: can the AI handle the latest human turn with its current context? "
    "CONTINUE or ACTION_NEEDED?"
)

COMPRESSOR_SYSTEM = """\
You compress a full voice AI conversation transcript into a dense boot payload
that will be loaded into the AI's memory before it speaks next.

The AI has a 4-minute memory window, so EVERYTHING must be in the payload.
If it's not in the payload, the AI won't remember it.

Target: 300-500 tokens (~1500-2500 characters). Be concise but complete.

AI Persona: {persona}

Output ONLY this format (no markdown, no preamble):
[PERSONA] {persona}
[KEY_FACTS] <bullet list: all names, places, numbers, decisions mentioned>
[TOPIC_HISTORY] <numbered list: topics in order, 1 sentence each>
[CURRENT_TOPIC] <what is being discussed right now>
[LAST_EXCHANGE] <what the human just asked/said and what the AI just said>
[TONE] <emotional tone to match: warm/curious/professional/excited>
[INSTRUCTION] <any specific instruction for the next response if relevant>
"""

COMPRESSOR_PROMPT = """\
=== FULL CONVERSATION TRANSCRIPT ===
{transcript}
=== END TRANSCRIPT ===

Additional context: {extra_context}

Generate the boot payload now.
"""

# ---------------------------------------------------------------------------
# Audio helpers
# ---------------------------------------------------------------------------

def pcm16_to_b64(raw: bytes) -> str:
    return base64.b64encode(raw).decode("ascii")

def b64_to_pcm16(b64: str) -> bytes:
    return base64.b64decode(b64)

def pcm16_to_float32(data: bytes):
    return np.frombuffer(data, dtype=np.int16).astype(np.float32) / 32768.0

def encode_voice_tokens(voice_name: str) -> list:
    """Encode voice name as [-999, ASCII...] for the pipeline model."""
    return [VOICE_SENTINEL] + [ord(c) for c in voice_name]

def encode_voice_with_text(voice_name: str, text_tokens: list[int]) -> list:
    """Dual-sentinel encoding: [-999, voiceASCII..., -998, tok1, tok2...]
    Lets the pipeline model load BOTH a voice prompt AND a text instruction.
    """
    return ([VOICE_SENTINEL]
            + [ord(c) for c in voice_name]
            + [VOICE_TEXT_SENTINEL]
            + text_tokens)

# ---------------------------------------------------------------------------
# Transcript
# ---------------------------------------------------------------------------

class Transcript:
    """Thread-safe rolling transcript with delta tracking."""

    def __init__(self):
        self._lock       = threading.Lock()
        self._full       = ""
        self._sent       = 0    # chars sent to Detector since last reconnect
        self._compressed = 0    # chars sent to Compressor cache

    def append(self, text: str):
        with self._lock:
            self._full += text
            if len(self._full) > 200_000:
                trim = len(self._full) - 150_000
                self._full      = self._full[trim:]
                self._sent      = max(0, self._sent - trim)
                self._compressed = max(0, self._compressed - trim)

    def get(self) -> str:
        with self._lock:
            return self._full

    def unsent_for_detector(self) -> str:
        with self._lock:
            return self._full[self._sent:]

    def mark_sent_for_detector(self):
        with self._lock:
            self._sent = len(self._full)

    def reset_detector_sent(self):
        """Call on reconnect — will re-send from beginning."""
        with self._lock:
            self._sent = 0

    def new_chars_for_compressor(self) -> int:
        with self._lock:
            return len(self._full) - self._compressed

    def mark_compressed(self):
        with self._lock:
            self._compressed = len(self._full)

    def __len__(self):
        with self._lock:
            return len(self._full)

# ---------------------------------------------------------------------------
# Compressor — Gemini Flash REST with context caching
# ---------------------------------------------------------------------------

class Compressor:
    """
    Uses Gemini Flash via the google-genai REST API with context caching.
    Called on keepalive and ACTION_NEEDED to generate boot payloads.
    Cache is refreshed every ~CACHE_REFRESH_CHARS new transcript chars.
    """

    def __init__(self, api_key: str, persona: str, model: str = COMPRESSOR_MODEL):
        self._client     = live_genai.Client(api_key=api_key)
        self._model      = model
        self._persona    = persona
        self._cache      = None      # CachedContent name string
        self._cache_name = None
        self._lock       = threading.Lock()
        self._system     = COMPRESSOR_SYSTEM.format(persona=persona)
        print(f"  [compressor] Gemini Flash ({model}) + context caching (google-genai)")

    def compress(self, transcript: str, extra_context: str = "") -> str:
        """
        Generate a boot payload from the full transcript.
        Uses cached context when transcript is large enough.
        """
        with self._lock:
            # Refresh cache if transcript is large enough for caching to pay off
            if len(transcript) >= 4096 and self._cache_name is None:
                self._refresh_cache(transcript)
            elif len(transcript) >= 4096 and self._cache_name:
                # We have a cache — it was created with old transcript snapshot.
                # Use it as-is; new delta will be in the prompt.
                pass

            cache_name = self._cache_name

        try:
            if cache_name:
                # Use cached transcript prefix; append new delta + instruction
                new_delta = transcript[self._cache_snapshot_len:] if hasattr(self, '_cache_snapshot_len') else ""
                prompt_parts = []
                if new_delta:
                    prompt_parts.append(f"[NEW TRANSCRIPT DELTA]\n{new_delta}\n[END DELTA]\n")
                if extra_context:
                    prompt_parts.append(f"Additional context: {extra_context}\n")
                prompt_parts.append("Generate the boot payload now.")
                prompt = "".join(prompt_parts)

                resp = self._client.models.generate_content(
                    model=self._model,
                    contents=prompt,
                    config=live_types.GenerateContentConfig(
                        cached_content=cache_name,
                        max_output_tokens=600,
                        temperature=0.2,
                    ),
                )
            else:
                # No cache yet — direct call with full transcript
                prompt = COMPRESSOR_PROMPT.format(
                    transcript=transcript[-8000:],
                    extra_context=extra_context or "none",
                )
                resp = self._client.models.generate_content(
                    model=self._model,
                    contents=prompt,
                    config=live_types.GenerateContentConfig(
                        system_instruction=self._system,
                        max_output_tokens=600,
                        temperature=0.2,
                    ),
                )

            result = resp.text.strip() if resp.text else ""
            if len(result) > BOOT_PAYLOAD_MAX_CHARS:
                result = result[:BOOT_PAYLOAD_MAX_CHARS]
            return result

        except Exception as e:
            print(f"\n  [compressor] ERROR: {e}")
            return ""

    def _refresh_cache(self, transcript: str):
        """Upload transcript as cached content (called with lock held)."""
        if self._cache_name:
            try:
                self._client.caches.delete(name=self._cache_name)
            except Exception:
                pass
            self._cache_name = None

        try:
            cache = self._client.caches.create(
                model=self._model,
                config=live_types.CreateCachedContentConfig(
                    display_name="pp_transcript",
                    system_instruction=self._system,
                    contents=[f"=== FULL TRANSCRIPT ===\n{transcript}\n=== END ==="],
                    ttl=datetime.timedelta(hours=1),
                ),
            )
            self._cache_name = cache.name
            self._cache_snapshot_len = len(transcript)
            print(f"\n  [compressor] Cache created ({len(transcript)} chars)")
        except Exception as e:
            print(f"\n  [compressor] Cache failed ({e}) — using direct call")
            self._cache_name = None

    def refresh_cache_if_needed(self, transcript: str):
        """Call periodically to refresh cache with latest transcript."""
        with self._lock:
            if len(transcript) >= 4096:
                self._refresh_cache(transcript)

    def cleanup(self):
        with self._lock:
            if self._cache_name:
                try:
                    self._client.caches.delete(name=self._cache_name)
                except Exception:
                    pass

# ---------------------------------------------------------------------------
# Detector — Gemini Live persistent session
# ---------------------------------------------------------------------------

class Detector:
    """
    Persistent Gemini Live WebSocket session.

    Transcript deltas are fed silently (turn_complete=False).
    On every turn.boundary "human_end" event: evaluates (turn_complete=True).
    Reconnects at LIVE_SESSION_MAX_S, re-injecting the full transcript.
    """

    def __init__(self, api_key: str, persona: str,
                 transcript: Transcript,
                 model: str = DETECTOR_MODEL,
                 on_action=None):
        self._api_key    = api_key
        self._persona    = persona
        self._transcript = transcript
        self._model      = model
        self._on_action  = on_action   # async callback(reason, topic)
        self._pp_context = f"Initial persona: {persona}"

        self._client = live_genai.Client(
            api_key=api_key,
            http_options={"api_version": "v1beta"},
        )

        self._eval_event  = None   # asyncio.Event
        self._stop_event  = None
        self._session_task = None
        self._session_start = 0.0
        self._eval_count  = 0
        self._running     = False

        print(f"  [detector] Gemini Live ({model}) — eval on turn.boundary")

    def update_pp_context(self, boot_payload: str):
        """Called after each node.prime so Detector knows what PP knows."""
        self._pp_context = boot_payload[:500] if boot_payload else self._pp_context

    async def start(self):
        self._eval_event  = asyncio.Event()
        self._stop_event  = asyncio.Event()
        self._running     = True
        self._session_task = asyncio.create_task(self._session_loop())

    async def stop(self):
        self._running = False
        if self._stop_event:
            self._stop_event.set()
        if self._session_task:
            self._session_task.cancel()
            try:
                await self._session_task
            except asyncio.CancelledError:
                pass

    def trigger_eval(self):
        """Called when turn.boundary human_end received."""
        if self._eval_event and self._running:
            self._eval_event.set()

    def force_eval(self):
        """Manual trigger from keyboard."""
        self.trigger_eval()

    @property
    def status(self) -> dict:
        age = time.monotonic() - self._session_start if self._session_start else 0
        return {
            "running":    self._running,
            "session_age": f"{age:.0f}s",
            "eval_count": self._eval_count,
        }

    # ── Internal ──────────────────────────────────────────────────────────

    def _build_config(self) -> "live_types.LiveConnectConfig":
        system = DETECTOR_SYSTEM.format(
            persona=self._persona,
            current_pp_context=self._pp_context[:300],
        )
        return live_types.LiveConnectConfig(
            response_modalities=["TEXT"],
            system_instruction=live_types.Content(
                parts=[live_types.Part(text=system)]
            ),
        )

    async def _session_loop(self):
        """Reconnect loop — runs until stop() called."""
        consecutive_failures = 0
        while self._running and not self._stop_event.is_set():
            try:
                await self._run_one_session()
                consecutive_failures = 0
            except asyncio.CancelledError:
                break
            except Exception as e:
                if self._running:
                    consecutive_failures += 1
                    err = str(e)
                    # 1008 = Policy Violation — Live API not available for this key
                    if "1008" in err and consecutive_failures >= 2:
                        print(f"\n  [detector] Live API unavailable (1008 Policy Violation).")
                        print(f"  [detector] 📌 Your API key may not have Gemini Live access.")
                        print(f"  [detector] Stopping Live detector. Use --no-brain or check AI Studio access.")
                        self._running = False
                        break
                    print(f"\n  [detector] Session error: {e} — reconnecting in 3s")
                    await asyncio.sleep(3)

    async def _run_one_session(self):
        self._session_start = time.monotonic()
        self._transcript.reset_detector_sent()

        config = self._build_config()
        async with self._client.aio.live.connect(
                model=self._model, config=config) as session:

            print("\n  [detector] Live session opened.")

            # Inject full transcript for context continuity on reconnect
            full = self._transcript.get()
            if full:
                await session.send(
                    input=f"[TRANSCRIPT SO FAR]\n{full}\n[END]\n",
                    end_of_turn=False
                )
                self._transcript.mark_sent_for_detector()
                print(f"  [detector] Injected {len(full)} chars of transcript.")

            sender   = asyncio.create_task(self._sender(session))
            receiver = asyncio.create_task(self._receiver(session))

            try:
                done, pending = await asyncio.wait(
                    [sender, receiver],
                    return_when=asyncio.FIRST_COMPLETED,
                )
            finally:
                for t in [sender, receiver]:
                    t.cancel()
                    try: await t
                    except asyncio.CancelledError: pass

    async def _sender(self, session):
        """Feed new transcript deltas and fire eval prompts."""
        while self._running:
            # Reconnect if session too old
            if time.monotonic() - self._session_start > LIVE_SESSION_MAX_S:
                print("\n  [detector] Session age limit — reconnecting.")
                return

            # Feed any unsent transcript delta
            delta = self._transcript.unsent_for_detector()
            if delta:
                await session.send(input=delta, end_of_turn=False)
                self._transcript.mark_sent_for_detector()

            # Fire eval if triggered
            if self._eval_event.is_set():
                self._eval_event.clear()
                self._eval_count += 1
                print(f"\n  [detector] Evaluating (#{self._eval_count})...", end="", flush=True)
                await session.send(input=DETECTOR_EVAL_PROMPT, end_of_turn=True)

            await asyncio.sleep(0.02)

    async def _receiver(self, session):
        """Receive and parse Gemini's evaluation responses."""
        response_buf = ""
        async for chunk in session.receive():
            if not self._running:
                break
            text = getattr(chunk, "text", None) or ""
            if text:
                response_buf += text
                print(text, end="", flush=True)

            sc = getattr(chunk, "server_content", None)
            if sc and getattr(sc, "turn_complete", False):
                await self._handle_response(response_buf.strip())
                response_buf = ""
                print()

    async def _handle_response(self, text: str):
        if not text:
            return
        if "CONTINUE" in text and "ACTION_NEEDED" not in text:
            print(f"\n  [detector] ✓ CONTINUE")
            return
        if "ACTION_NEEDED" in text:
            reason = ""
            topic  = ""
            for line in text.splitlines():
                if line.startswith("[REASON]"):
                    reason = line[8:].strip()
                elif line.startswith("[TOPIC]"):
                    topic = line[7:].strip()
            print(f"\n  [detector] ⚡ ACTION_NEEDED — {reason}")
            if self._on_action:
                await self._on_action(reason, topic)
        else:
            print(f"\n  [detector] Unexpected: {text[:80]}")

# ---------------------------------------------------------------------------
# PersonaPlexClient
# ---------------------------------------------------------------------------

class PersonaPlexClient:

    def __init__(self, args):
        self.args       = args
        self.ws         = None
        self.loop       = None
        self.transcript = Transcript()
        self.node_state = {"active": True, "standby": False,
                           "filler": False, "state": "hot_only"}

        self._audio_out_q: queue.Queue = queue.Queue(maxsize=200)
        self._action_in_progress = False   # guard against double ACTION_NEEDED
        self._last_switch_t      = time.monotonic()

        # ── Compressor (REST) ─────────────────────────────────────────────
        self.compressor: Optional[Compressor] = None
        if not args.no_brain and _REST_GENAI and args.google_api_key:
            self.compressor = Compressor(
                api_key=args.google_api_key,
                persona=args.persona,
                model=args.compressor_model,
            )

        # ── Detector: Gemini Live ─────────────────────────────────────────────
        self.detector = None
        if not args.no_brain and _LIVE_GENAI and args.google_api_key and self.compressor:
            self.detector = Detector(
                api_key=args.google_api_key,
                persona=args.persona,
                transcript=self.transcript,
                model=args.detector_model,
                on_action=self._on_action_needed,
            )
        elif not args.no_brain:
            missing = []
            if not _LIVE_GENAI:         missing.append("pip install google-genai")
            if not args.google_api_key: missing.append("--google-api-key / $env:GOOGLE_API_KEY")
            print(f"  Brain: disabled \u2014 {', '.join(missing)}")
        else:
            print("  Brain: disabled (--no-brain)")

    # ── Brain callbacks ───────────────────────────────────────────────────

    async def _on_action_needed(self, reason: str, topic: str):
        """
        Detector says ACTION_NEEDED:
        1. Switch to Filler immediately (human hears "hold on...")
        2. Call Compressor in background to generate boot payload
        3. Prime Standby with payload
        4. On node.standby_ready → switch Standby in + reset Filler
        """
        if self._action_in_progress:
            print("\n  [brain] ACTION_NEEDED ignored — one already in progress")
            return
        self._action_in_progress = True

        print(f"\n  [ACTION] Reason: {reason}")
        print(f"  [ACTION] Topic:  {topic}")

        # Step 1: Filler immediately
        await self.send_node_switch("filler")

        # Step 2+3: Compress and prime in background (don't block)
        asyncio.create_task(self._compress_and_prime(
            extra_context=f"User needs info about: {topic}. Reason: {reason}"
        ))

    async def _compress_and_prime(self, extra_context: str = ""):
        """Background task: call Compressor then prime Standby."""
        try:
            t0 = time.monotonic()
            payload = await asyncio.get_event_loop().run_in_executor(
                None,
                lambda: self.compressor.compress(
                    self.transcript.get(), extra_context
                )
            )
            elapsed = time.monotonic() - t0
            print(f"\n  [compressor] {elapsed:.1f}s → {payload[:80]}...")

            if payload:
                self.transcript.mark_compressed()
                if self.detector:
                    self.detector.update_pp_context(payload)
                await self.send_node_prime(payload)
        except Exception as e:
            print(f"\n  [compressor] compress_and_prime error: {e}")
            self._action_in_progress = False

    async def _keepalive_loop(self):
        """Trigger a node refresh every KEEPALIVE_INTERVAL_S seconds."""
        await asyncio.sleep(KEEPALIVE_INTERVAL_S)  # don't fire immediately
        while True:
            if self.compressor and self.ws and not self._action_in_progress:
                print("\n  [keepalive] Refreshing PP context...")
                asyncio.create_task(self._keepalive_refresh())
            await asyncio.sleep(KEEPALIVE_INTERVAL_S)

    async def _keepalive_refresh(self):
        """Generate boot payload and send node.refresh."""
        try:
            t0 = time.monotonic()
            payload = await asyncio.get_event_loop().run_in_executor(
                None,
                lambda: self.compressor.compress(self.transcript.get())
            )
            elapsed = time.monotonic() - t0
            print(f"\n  [keepalive] {elapsed:.1f}s → {payload[:80]}...")
            if payload:
                self.transcript.mark_compressed()
                if self.detector:
                    self.detector.update_pp_context(payload)
                await self._send({
                    "type":   "node.refresh",
                    "prompt": payload,
                    "voice":  self.args.voice.upper() if self.args.voice else "",
                })
        except Exception as e:
            print(f"\n  [keepalive] Error: {e}")

    # ── WebSocket helpers ─────────────────────────────────────────────────

    async def _send(self, msg: dict):
        if self.ws:
            await self.ws.send(json.dumps(msg))

    async def send_node_switch(self, to: str):
        print(f"\n  → node.switch to={to}")
        await self._send({"type": "node.switch", "to": to})

    async def send_node_prime(self, prompt: str):
        print(f"\n  → node.prime: {prompt[:80]}...")
        await self._send({
            "type": "node.prime", "target": "standby", "prompt": prompt
        })

    async def send_node_stop(self, target: str = "filler"):
        print(f"\n  → node.stop target={target}")
        await self._send({"type": "node.stop", "target": target})

    # ── Message handler ───────────────────────────────────────────────────

    async def _on_message(self, raw: str):
        try:
            ev = json.loads(raw)
        except Exception:
            return

        t = ev.get("type", "")

        if t == "session.created":
            sid = ev.get("session", {}).get("id", ev.get("id", "?"))
            print(f"  session.created  id={sid}")

        elif t == "session.updated":
            print("  session.updated")

        elif t == "session.ready":
            print("  session.ready ✓ — PP active, audio flowing...")
            if self.detector:
                await self.detector.start()
                print(f"  [detector] Started.")

        elif t == "response.audio.delta":
            b64 = ev.get("delta", "")
            if b64:
                pcm = pcm16_to_float32(b64_to_pcm16(b64))
                try:
                    self._audio_out_q.put_nowait(pcm)
                except queue.Full:
                    pass

        elif t == "transcript.delta":
            text = ev.get("text", "")
            if text:
                self.transcript.append(text)
                print(f"\r  AI: ...{self.transcript.get()[-70:]}", end="", flush=True)

        elif t == "turn.boundary":
            speaker = ev.get("speaker", "")
            if speaker == "human_end" and len(self.transcript) >= BRAIN_MIN_CHARS:
                # Human stopped speaking — trigger Detector evaluation
                if self.detector:
                    self.detector.trigger_eval()

        elif t == "node.status":
            self.node_state = {k: ev.get(k) for k in
                               ("active","standby","filler","state")}
            s = self.node_state
            print(f"\n  [node.status] active={s['active']} standby={s['standby']} "
                  f"filler={s['filler']} state={s['state']}")

        elif t == "node.standby_ready":
            print("\n  [node.standby_ready] → switching standby in...")
            await self.send_node_switch("standby")
            self._last_switch_t = time.monotonic()
            # Reset filler and action guard
            await self.send_node_stop("filler")
            self._action_in_progress = False

        elif t in ("error", "session_error"):
            msg = ev.get("error", {}).get("message", ev.get("message", "?"))
            print(f"\n  [ERROR] {msg}")

    # ── Mic sender ────────────────────────────────────────────────────────

    async def _mic_sender(self):
        if not sd:
            print("  [mic] sounddevice not available — no audio input")
            await asyncio.sleep(99999)
            return
        mic_q: queue.Queue = queue.Queue()
        sent_frames = 0
        loud_frames  = 0

        def callback(indata, frames, time_cb, status):
            if status:
                pass  # ignore overflow etc
            mic_q.put_nowait(bytes(indata))

        device_kw = {}
        if self.args.input_device is not None:
            device_kw["device"] = self.args.input_device

        try:
            stream_ctx = sd.RawInputStream(
                samplerate=INPUT_RATE, channels=1, dtype="int16",
                blocksize=FRAME_SAMPLES_IN, callback=callback,
                **device_kw)
        except Exception as e:
            print(f"  [mic] Failed to open input device: {e}")
            print(f"  [mic] Try: python tools/brain_client.py --list-devices")
            await asyncio.sleep(99999)
            return

        print(f"  [mic] Input open — talk into your mic (use headphones!).")
        with stream_ctx:
            while True:
                try:
                    raw = mic_q.get(timeout=0.2)
                except queue.Empty:
                    continue
                sent_frames += 1
                # Level monitor every 5s (62 frames = ~5s)
                arr = np.frombuffer(raw, dtype=np.int16).astype(np.float32)
                if np.abs(arr).max() > 300:
                    loud_frames += 1
                if sent_frames % 62 == 0:
                    level = "OK" if loud_frames > 5 else "SILENT (check mic / headset)"
                    print(f"\r  [mic] level={level} ({loud_frames}/62 loud frames)      ",
                          end="", flush=True)
                    loud_frames = 0
                await self._send({
                    "type":  "input_audio_buffer.append",
                    "audio": pcm16_to_b64(raw),
                })

    # ── Speaker ───────────────────────────────────────────────────────────

    def _speaker_thread(self):
        if not sd:
            return
        device_kw = {}
        if self.args.output_device is not None:
            device_kw["device"] = self.args.output_device
        stream = sd.OutputStream(
            samplerate=OUTPUT_RATE, channels=1, dtype="float32",
            **device_kw)
        stream.start()
        try:
            while True:
                try:
                    pcm = self._audio_out_q.get(timeout=0.5)
                    stream.write(pcm.reshape(-1, 1))
                except queue.Empty:
                    continue
                except Exception as e:
                    print(f"\n[speaker] {e}")
        finally:
            stream.stop()
            stream.close()

    # ── Keyboard commands ─────────────────────────────────────────────────

    async def _command_loop(self):
        print("""
  Commands:
    s        — switch to standby (if primed)
    f        — switch to filler (immediate)
    r        — reset filler
    k        — force keepalive refresh now
    e        — force Detector evaluation now
    p <text> — prime standby with custom prompt
    t        — print full transcript
    n        — print node status
    d        — print Detector status
    q        — quit
""")
        loop = asyncio.get_event_loop()
        while True:
            try:
                line = await loop.run_in_executor(None, sys.stdin.readline)
            except Exception:
                break
            line = line.strip()
            if not line:
                continue
            if   line == "q":
                if self.ws: await self.ws.close()
                break
            elif line == "s": await self.send_node_switch("standby")
            elif line == "f": await self.send_node_switch("filler")
            elif line == "r": await self.send_node_stop("filler")
            elif line == "k": asyncio.create_task(self._keepalive_refresh())
            elif line == "e":
                if self.detector: self.detector.force_eval()
                else: print("  Detector not running.")
            elif line.startswith("p "):
                await self.send_node_prime(line[2:].strip())
            elif line == "t":
                print(f"\n--- Transcript ---\n{self.transcript.get()}\n---")
            elif line == "n":
                print(f"\n  Node state: {self.node_state}")
            elif line == "d":
                if self.detector:
                    print(f"\n  Detector: {self.detector.status}")
                else:
                    print("  Detector not running.")
            else:
                print(f"  Unknown: {line!r}")

    # ── Session setup ─────────────────────────────────────────────────────

    async def _send_session_update(self):
        session: dict = {
            "instructions":  self.args.persona,
            "filler_prompt": self.args.filler,
        }
        v = self.args.voice.upper()
        if v in VOICE_NAMES:
            session["text_prompt_tokens"] = encode_voice_tokens(v)
            # Filler gets same voice + the "hold on" text instruction
            # (dual-sentinel: [-999, voiceASCII..., -998, textTok1, ...])
            if FILLER_TEXT_TOKENS:
                session["filler_text_tokens"] = encode_voice_with_text(v, FILLER_TEXT_TOKENS)
            else:
                # No text tokens yet — filler gets voice only, no instruction.
                # Run `python3 tools/check_voices.py` on Spark to get tokens.
                session["filler_text_tokens"] = encode_voice_tokens(v)
                print("  [warn] FILLER_TEXT_TOKENS empty — run check_voices.py on Spark")
        await self._send({"type": "session.update", "session": session})
        print("  Sent session.update, waiting for session.ready...")

    # ── Main ──────────────────────────────────────────────────────────────

    async def run(self):
        url = f"ws://{self.args.host}:{self.args.port}/v1/realtime"
        print(f"Connecting to {url} ...")
        threading.Thread(target=self._speaker_thread, daemon=True).start()
        self.loop = asyncio.get_event_loop()

        try:
            async with websockets.connect(url, max_size=32*1024*1024) as ws:
                self.ws = ws
                print("Connected!")
                raw = await asyncio.wait_for(ws.recv(), timeout=10)
                await self._on_message(raw)
                await self._send_session_update()
                await asyncio.gather(
                    self._receive_loop(),
                    self._mic_sender(),
                    self._command_loop(),
                    self._keepalive_loop(),
                )
        except websockets.exceptions.ConnectionRefusedError:
            print(f"\nERROR: Connection refused at {url}")
        except asyncio.TimeoutError:
            print("\nERROR: Timeout waiting for server")
        except KeyboardInterrupt:
            print("\nInterrupted.")
        finally:
            if self.detector:
                await self.detector.stop()
            if self.compressor:
                self.compressor.cleanup()

    async def _receive_loop(self):
        async for msg in self.ws:
            await self._on_message(msg)

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def pick_voice() -> str:
    groups = [
        ("Natural Female", ["NATF0","NATF1","NATF2","NATF3"]),
        ("Natural Male",   ["NATM0","NATM1","NATM2","NATM3"]),
        ("Varied Female",  ["VARF0","VARF1","VARF2","VARF3","VARF4"]),
        ("Varied Male",    ["VARM0","VARM1","VARM2","VARM3","VARM4"]),
    ]
    print("\n  Available voices:")
    idx, flat = 1, []
    for name, voices in groups:
        print(f"    ── {name} ──")
        for v in voices:
            print(f"    {idx:2d}. {v}")
            flat.append(v)
            idx += 1
    print("     0. (no voice prompt — use default)\n")
    while True:
        try:
            sel = int(input("  Select voice [1-18, 0=default]: ").strip())
            if sel == 0: return ""
            if 1 <= sel <= len(flat):
                print(f"  Selected: {flat[sel-1]}")
                return flat[sel-1]
        except (ValueError, EOFError):
            pass


def main():
    p = argparse.ArgumentParser(description="PersonaPlex v3 Brain Client")
    p.add_argument("--host",  default="192.168.2.117")
    p.add_argument("--port",  type=int, default=8998)
    p.add_argument("--persona",
                   default="You are a helpful, friendly AI assistant.")
    p.add_argument("--filler",
                   default="Hold on, I'm working on that for you. Just a moment.")
    p.add_argument("--voice", default="",
                   help="Voice name e.g. NATF0, or blank for interactive")
    p.add_argument("--google-api-key",
                   default=os.environ.get("GOOGLE_API_KEY", ""),
                   dest="google_api_key")
    p.add_argument("--detector-model",  default=DETECTOR_MODEL,
                   dest="detector_model")
    p.add_argument("--compressor-model", default=COMPRESSOR_MODEL,
                   dest="compressor_model")
    p.add_argument("--no-brain",  action="store_true")
    p.add_argument("--no-live",   action="store_true",
                   help="Use Flash REST detector instead of Gemini Live WebSocket")
    p.add_argument("--input-device",  type=int, default=None, dest="input_device",
                   help="Sounddevice input device index (see --list-devices)")
    p.add_argument("--output-device", type=int, default=None, dest="output_device",
                   help="Sounddevice output device index (see --list-devices)")
    p.add_argument("--list-devices", action="store_true", dest="list_devices",
                   help="Print audio devices and exit")
    args = p.parse_args()

    if args.list_devices:
        if sd:
            print("\nAudio devices:")
            print(sd.query_devices())
            default_in  = sd.default.device[0]
            default_out = sd.default.device[1]
            print(f"\nDefault input : {default_in} — {sd.query_devices(default_in)['name']}")
            print(f"Default output: {default_out} — {sd.query_devices(default_out)['name']}")
        else:
            print("sounddevice not available")
        sys.exit(0)

    detector_name = "disabled"
    if not args.no_brain and args.google_api_key:
        detector_name = ("Flash-REST (--no-live)" if args.no_live
                         else f"Live ({args.detector_model})")
    brain_status = "disabled" if args.no_brain else (
        f"Detector={detector_name} + Compressor={args.compressor_model}"
    )
    print(f"""
PersonaPlex v3 Brain Client
  Server      : {args.host}:{args.port}
  Persona     : {args.persona[:60]}
  Filler      : {args.filler[:60]}
  Brain       : {brain_status}
  Keepalive   : every {KEEPALIVE_INTERVAL_S}s (~{KEEPALIVE_INTERVAL_S//60}m {KEEPALIVE_INTERVAL_S%60}s)
  Input dev   : {args.input_device if args.input_device is not None else 'default'}
  Output dev  : {args.output_device if args.output_device is not None else 'default'}
  Tip         : Use headphones to prevent AI audio feedback loop!
""")

    if not args.voice:
        args.voice = pick_voice()

    try:
        asyncio.run(PersonaPlexClient(args).run())
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
